version: "3.8"
services:

  db:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
        - db-data:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
        - dev
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
        - dev

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_docker
    ports:
      - "8741:80"
    volumes:
      - ./project:/var/www/html/
    restart: always
    networks:
        - dev




networks:
    dev:

volumes:
    db-data:
